config/routes.rb
Rails.application.routes.draw do

  root 'sessions#new'

  get 'sessions/new'
  get 'sessions/destroy'
  post 'sessions/create'

  get 'download(/:user_account_id/:id)' => 'uploaded_files#download', as: 'download'

  get 'search(/:user_account_id/:term)' => 'uploaded_files#search', as: 'search_user_account_uploaded_files'

  resources :user_accounts do
    resources :uploaded_files
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/uploaded_file.rb
class UploadedFile < ApplicationRecord
  validates :user_account_id, :filename, :savetime, presence: true

  belongs_to :user_account
end

app/models/user_account.rb
class UserAccount < ApplicationRecord
  validates :firstname, :lastname, :email,
            :password, presence: true
  validates :email, uniqueness: true, on: :create
  #validates :password, length: { minimum: 8 }
  validates_format_of :email, :with => /\A[\w]+@[\w]+\.+[\w]+\z/


  has_secure_password

  has_many :uploaded_files
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def current_user
    UserAccount.where(id: session[:user_account_id]).first
  end
  helper_method :current_user

  def authorize
    redirect_to root_path unless current_user
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    @user = UserAccount.find_by_email(params[:email])
    if @user && @user.authenticate(params[:password])
      session[:user_account_id] = @user.id
      redirect_to user_account_uploaded_files_path(@user), notice: 'Logged in.'
    else
      flash.now[:notice] = 'User account not found.'
      render :new
    end
  end

  def destroy
    session[:user_account_id] = nil
    redirect_to root_path, notice: 'Logged out.'
  end
end

app/controllers/uploaded_files_controller.rb
class UploadedFilesController < ApplicationController

  before_action :authorize

  def index
    @user_account = UserAccount.find(params[:user_account_id])
    @uploaded_files = @user_account.uploaded_files.order(filename: :desc).all
  end

  def new
    @user_account = UserAccount.find(params[:user_account_id])
    @uploaded_file = UploadedFile.new(:user_account => @user_account)
  end

  def create
    @user_account = UserAccount.find(params[:user_account_id])
    fileUpload = params[:uploaded_file][:file_to_upload]

    # Ensure that uploaded_file is not nil.
    if fileUpload != nil

      uploaded_filename = fileUpload.original_filename

      # Add timestamp to filename for uniqueness.
      t = Time.now
      ts = t.strftime("%y%m%d%H%M%S")

      @uploaded_file = UploadedFile.new(uploaded_file_params)
      @uploaded_file.user_account = @user_account
      @uploaded_file.filename = uploaded_filename
      @uploaded_file.size = fileUpload.size
      @uploaded_file.savetime = ts

      if @uploaded_file.save

        filename = file_name(uploaded_filename, @user_account.id, ts)

        if not File.exist?(filename)
          File.open(filename, 'wb') do |file|
            file.write(fileUpload.read)
          end
        end
        
        @uploaded_files = @user_account.uploaded_files.order(filename: :desc).all
        render :index
      else

        render :new
      end

    else

      # No file was selected, uploaded_file is nil.
      @uploaded_file = UploadedFile.new(:user_account => @user_account)
      @uploaded_file.errors.add(:base, "No file chosen")
      render :new
    end
  end

  def show
  end

  def download
    @user_account = UserAccount.find(params[:user_account_id])
    @uploaded_file = @user_account.uploaded_files.find(params[:id])
    filename = file_name(@uploaded_file.filename,
                         @user_account.id,
                         @uploaded_file.savetime)

    send_file(filename,
              filename: @uploaded_file.filename,
              disposition: 'attachment' )
   end

  def destroy
    @user_account = UserAccount.find(params[:user_account_id])
    id = params[:id]
    @uploaded_file = @user_account.uploaded_files.find(id)

    filename = file_name(@uploaded_file.filename,
                         @user_account.id,
                         @uploaded_file.savetime)

    File.delete(filename) if File.exist?(filename)
    @uploaded_file.destroy

    redirect_to user_account_uploaded_files_path(@user_account)
  end

  def search
    @user_account = UserAccount.find(params[:user_account_id])
    term = params[:term]
    searchTerm = "%#{term}%"
    @uploaded_files = @user_account.uploaded_files.where("filename like ?", searchTerm)
    render :index
  end

  private

  # Construct a unique filename given the original filename,
  # user account, and a timestamp. i.e. "8.170708141436_Test.pdf"
  # Set the path to the root/public/uploads directory.
  def file_name (filename, user_account_id, timestamp)
    filename =  "#{user_account_id}.#{timestamp}_#{filename}"
    Rails.root.join('public', 'uploads', filename)
  end

  def uploaded_file_params
    params.require(:uploaded_file).permit(:description)
  end
end

app/controllers/user_accounts_controller.rb
class UserAccountsController < ApplicationController
  def index
    @user_accounts = UserAccount.order('firstname').all
  end

  def new
    @user_account = UserAccount.new
  end

  def create
    @user_account = UserAccount.new(user_account_params)

    if @user_account.save

      session[:user_account_id] = @user_account.id
      redirect_to user_account_uploaded_files_path(@user_account)
    else

      render :new
    end
  end

  def edit
    id = params[:id]
    @user_account = UserAccount.find(id)
  end

  def update
    id = params[:id]
    @user_account = UserAccount.find(id)
    if @user_account.update(user_account_params)

      redirect_to user_account_uploaded_files_path(@user_account)
    else
      
      render 'edit'
    end
  end

  private
  def user_account_params
    params.require(:user_account).permit(:firstname, :lastname, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/uploaded_files_helper.rb
module UploadedFilesHelper
end

app/helpers/user_accounts_helper.rb
module UserAccountsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsFileManager</title>
    <%= csrf_meta_tags %>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

   <!-- Custom styles for login template -->
    <%= stylesheet_link_tag    'signin',      media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
    <%= yield %>
    </div>

      <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous">
    </script>
  </body>
</html>

app/views/uploaded_files/index.html.erb
<% if current_user %>
  <div>
  <em>Logged in as <%= current_user.email %></em>
  <div class="btn-group" role="group" aria-label="...">
    <%= link_to edit_user_account_path(current_user), class: "btn btn-info btn-sm" do %>
    <i class="glyphicon glyphicon-edit"></i> Edit Account
    <% end %>
    <%= link_to sessions_destroy_path, class: "btn btn-default btn-sm" do %>
    <i class="glyphicon glyphicon-off"></i> Log Out
    <% end %>
  </div>
  </div>
<% end %>

<h1>Files Directory</h1>

<p><%= link_to new_user_account_uploaded_file_path(@user_account), class: "btn btn-primary btn-md" do %>
    <i class="glyphicon glyphicon-plus"></i> Add File
  <% end %>
</p>

<p>
<%= form_tag search_user_account_uploaded_files_path(@user_account), :method => :get do %>
  <%= hidden_field_tag :user_account_id, @user_account.id %>
  <%= text_field_tag :term %>
  <div class="btn-group" role="group" aria-label="...">
  <%= button_tag type: "submit", class: "btn btn-primary btn-sm" do %>
  <i class="glyphicon glyphicon-search"></i> Search
  <% end %>
  <%= link_to user_account_uploaded_files_path(@user_account), class: "btn btn-default btn-sm" do %>
    <i class="glyphicon glyphicon-remove-circle"></i> Clear
  <% end %>
  </div>
<% end %>
</p>

<% if @uploaded_files.length == 0 %>
  <h2>No files found</h2>
<% else %>
  <table class="table table-bordered table-striped">
    <thead>
      <tr>
        <th>Filename</th>
        <th>Description</th>
        <th>Create Date</th>
        <th>Size</th>
        <th></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @uploaded_files.each do |uploaded_file| %>
      <tr>
        <td><%= uploaded_file.filename %></td>
        <td><%= uploaded_file.description %></td>
        <td><%= uploaded_file.created_at.to_s %></td>
        <td><%= number_to_human_size(uploaded_file.size) %></td>
        <td><%= link_to "Download", download_path(@user_account, uploaded_file), class: "btn btn-default btn-sm" %></td>
        <td><%= link_to "Delete", [@user_account, uploaded_file], method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-default btn-sm" %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/uploaded_files/new.html.erb
<h1>File Upload</h1>

<br>
<%= form_for [@user_account, @uploaded_file], :html => {:multipart => true} do |f| %>
  <div class="form-group">
    <%= label_tag :select, "Select file:", for: "file_to_upload", class: "sr-only" %>
    <%= f.file_field :file_to_upload %>
  </div>
  <div class="form-group">
    <label>Description:</label>
    <%= f.text_area :description, {:rows=>2, :maxlength=>'140', :class=>'form-control'} %>
  </div>
  <div class="form-group">
    <%= submit_tag "Upload" %>
  </div>
<% end %>

<br>
<% if @uploaded_file.errors.any? %>
  <div id="error_explanation" class="alert alert-danger" align="left">
  <%= pluralize(@uploaded_file.errors.count, "error") %>
    prohibited this file from being saved:
  <ul>
  <% @uploaded_file.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
  </ul>
</div>
<% end %>

<p><%= link_to "Back", user_account_uploaded_files_path(@user_account) %></p>

app/views/user_accounts/_form.html.erb
<h2>Please enter your details.</h2>

<div class="container">
<%= form_for @user_account, class: "form-horizontal" do |f| %>
  <div class="row">
      <label class="col-sm-2 control-label">First Name:</label>
      <div class="col-sm-10">
        <%=f.text_field :firstname, class: "form-control input-md" %>
      </div>
  </div>
  <div class="row">
    <label class="col-sm-2 control-label">Last Name:</label>
    <div class="col-sm-10">
      <%=f.text_field :lastname, class: "form-control input-md" %>
    </div>
  </div>
  <div class="row">
    <label class="col-sm-2 control-label">Email Address:</label>
    <div class="col-sm-10">
      <%=f.text_field :email, class: "form-control input-md" %>
    </div>
  </div>
  <div class="row">
    <label class="col-sm-2 control-label">Password:</label>
    <div class="col-sm-10">
      <%=f.password_field :password, class: "form-control input-md" %>
    </div>
  </div>
  <div class="row">
    <label class="col-sm-2 control-label">Password Confirmation:</label>
    <div class="col-sm-10">
      <%=f.password_field :password_confirmation, class: "form-control input-md" %>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-offset-2 col-sm-10">
        <%= f.submit "Save" %>
    </div>
  </div>
<% end %>
</div>

<% if @user_account.errors.any? %>
<br>
  <div id="error_explanation" class="alert alert-danger" align="left">
  <%= pluralize(@user_account.errors.count, "error") %>
  <ul>
    <% @user_account.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
  </div>
<% end %>

app/views/user_accounts/edit.html.erb
<h1>Edit User Account Page</h1>
<%= render 'form' %>
<p><%= link_to "Back", user_account_uploaded_files_path(@user_account) %></p>

app/views/user_accounts/new.html.erb
<h1>New User Account Page</h1>
<%= render 'form' %>
<p></p>
<p><%= link_to "Back", sessions_new_path %></p>